source :rubygems
source "http://gems.rubyforge.org"
source "http://gems.github.com"

gem "MINT-statemachine",:path => "../statemachine" #"1.2.2"
gem "MINT-scxml", :path => "../scxml"
gem "rspec", "1.3.1"
gem "dm-core","0.10.2"
gem "dm-rinda-adapter","0.1.0"
gem "cassowary","1.0.0"
gem "eventmachine", "0.12.10"
gem "rake","0.9.2"
gem "rmagick","2.12.2"
gem "hoe", "2.9.6"
gem "newgem"
gem "rdoc"
gem "json"
gem "redis"
